function SummaryCard({ summary, resolutionSummary }) {
  const matchRate = Number(summary?.match_rate_pct ?? 0)
  const totalTime = Number(summary?.total_time_sec ?? 0)
  const recordsPerSecond = Number(summary?.records_per_sec ?? 0)
  const closeRate = Number(resolutionSummary?.auto_close_rate_pct ?? 0)
  const humanReview = Number(resolutionSummary?.needs_human_review_count ?? 0)
  return <section className="summary-card" aria-label="Run summary"><div className="resolution-banner"><strong>{closeRate.toFixed(1)}%</strong><div><span>closed automatically</span><b>{humanReview} items need your review</b></div></div><div className="match-rate"><div className="rate-ring" style={{ '--rate': `${Math.min(Math.max(matchRate, 0), 100) * 3.6}deg` }}><div><strong>{matchRate.toFixed(1)}%</strong><span>match rate</span></div></div><div className="run-performance"><SummaryStat label="Records processed" value={summary?.records_processed ?? 0} /><SummaryStat label="Run time" value={`${totalTime.toFixed(2)}s`} /><SummaryStat label="Records / sec" value={recordsPerSecond.toFixed(0)} /></div></div><div className="summary-stats"><SummaryStat label="Settlement batches" value={summary?.total_settlement_batches ?? 0} /><SummaryStat label="Matched batches" value={summary?.matched_batches ?? 0} /><SummaryStat label="Total exceptions" value={summary?.total_exceptions ?? 0} emphasis /><div className="llm-stat"><span>LLM reasoning</span><strong className={summary?.llm_available ? 'status-on' : 'status-off'}>{summary?.llm_available ? 'Available' : 'Unavailable'}</strong></div></div></section>
}
function SummaryStat({ label, value, emphasis }) { return <div className="summary-stat"><strong className={emphasis ? 'stat-emphasis' : ''}>{value}</strong><span>{label}</span></div> }
export default SummaryCard